### ISSUE TITLE
missing parentheses causing error message

### ISSUE THREAD

**Issue by tedmoorman** [sadukie/dataweekender-cu5-gremlin-api#1]
`EDGES.append(f\"g.V().has('name','DataWeekender').addE('covers').to(g.V().hasLabel('Topic').has('name','{topic['Node Name']}')\")"`
should be
`EDGES.append(f\"g.V().has('name','DataWeekender').addE('covers').to(g.V().hasLabel('Topic').has('name','{topic['Node Name']}'))\")"`

`"EDGES.append(\"g.V().has('name','You').addE('interested in').to(g.V().hasLabel('Topic').has('name','Azure')\")"`
should be
`"EDGES.append(\"g.V().has('name','You').addE('interested in').to(g.V().hasLabel('Topic').has('name','Azure')\")"`

There is a parentheses missing in both.

**Comment by sadukie** [comment]
Thank you for reporting this. The fix will be up shortly!
