### ISSUE TITLE
apostrophes causing error messages

### ISSUE THREAD

**Issue by tedmoorman** [sadukie/dataweekender-cu5-gremlin-api#2]
Consider adding to `df.Label.unique()`, the following:

`df['Node Name'] = df['Node Name'].apply(lambda x: str(x).replace("'", ""))`

I'm getting Gremlin error messages from the apostrophes. Not sure if there's a better solution.

**Comment by sadukie** [comment]
I would rather not remove the apostrophes, as that is part of the data and can change the meeting if removed. I am testing a solution with the apostrophes escaped so that we can preserve the apostrophes.

**Comment by sadukie** [comment]
Looks like escaping the apostrophes will work.
<img width="339" alt="image" src="https://github.com/sadukie/dataweekender-cu5-gremlin-api/assets/106202/5bc0f60f-b15f-4260-867c-7a36cafbcc66">

I ran `g.V().values('name')` to look at just the names. The title with `that's` is one that uses a regular single quote (as opposed to some that use the smart quotes).
